#!/usr/bin/env python3
"""Write docs/COVERAGE.md: for every country, which boards cover it and on what terms.

    python tools/coverage_md.py path/to/iso_countries.json > docs/COVERAGE.md

The country list is the CRM's `backend/app/cv/iso_countries.json` (ISO-3166 + UN regions); the
board facts come from each portal's SKILL.md frontmatter via service.portals.discover(). Boards are
classed as: official (government / public employment service), keyed (free API key needed), open
(no key), fallback (low quota, used only when nothing else covers a country). A country with no
board is listed as such — the engine never pretends.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from service import portals as P  # noqa: E402


def klass(p: P.Portal) -> str:
    if p.official:
        return "official"
    if p.fallback:
        return "fallback"
    if p.requires_env:
        return "keyed"
    return "open"


def main(iso_path: str) -> None:
    iso = json.loads(Path(iso_path).read_text(encoding="utf-8"))
    ps = [p for p in P.discover().values() if p.enabled or p.requires_env]   # shipped-off demo boards are omitted
    by_class = Counter(klass(p) for p in ps)
    lines = [
        "# Country coverage",
        "",
        "Generated by `tools/coverage_md.py` from each portal's SKILL.md frontmatter — regenerate after adding a board.",
        "",
        f"Boards: {len(ps)} — {by_class['official']} official, {by_class['open']} open aggregators, "
        f"{by_class['keyed']} needing a free key, {by_class['fallback']} fallback.",
        "",
        "| board | class | countries | sponsorship signal |",
        "|---|---|---|---|",
    ]
    for p in sorted(ps, key=lambda p: (klass(p) != "official", klass(p), p.name)):
        cc = "worldwide" if p.worldwide else ", ".join(p.countries) if len(p.countries) <= 8 else f"{len(p.countries)} countries"
        key = f" (`{'`, `'.join(p.requires_env)}`)" if p.requires_env else ""
        lines.append(f"| {p.title or p.name} | {klass(p)}{key} | {cc} | {p.sponsor_signal or '—'} |")
    lines += ["", "## By country", "",
              "official = a government board; open = aggregator, no key; keyed = free key needed; worldwide boards "
              "(remote-job feeds, Google-for-Jobs fallback) apply everywhere and are not repeated per row.", "",
              "| country | region | official | open | keyed | fallback only |", "|---|---|---|---|---|---|"]
    world = [p for p in ps if p.worldwide]
    world_open = [p.title or p.name for p in world if klass(p) == "open"]
    world_fallback = [p.title or p.name for p in world if p.fallback]
    lines.insert(len(lines) - 2, f"Worldwide open boards: {', '.join(world_open) or '—'}. Worldwide fallback: {', '.join(world_fallback) or '—'}.")
    lines.insert(len(lines) - 2, "")
    none_at_all = []
    for c in iso:
        local = [p for p in ps if not p.worldwide and c["code"] in p.countries]
        off = [p.title or p.name for p in local if p.official]
        opn = [p.title or p.name for p in local if klass(p) == "open"]
        keyed = [p.title or p.name for p in local if klass(p) == "keyed"]
        only_fallback = not local
        if only_fallback:
            none_at_all.append(c["code"])
        lines.append(f"| {c['name']} ({c['code']}) | {c['subregion']} | {', '.join(off) or '—'} | {', '.join(opn) or '—'} | "
                     f"{', '.join(keyed) or '—'} | {'yes' if only_fallback else ''} |")
    lines += ["", f"Countries with no country-specific board ({len(none_at_all)} of {len(iso)}): only the worldwide remote feeds and, "
              "once a key is set, the Google-for-Jobs fallback apply. The sponsor registers work for any country a CSV/XLSX is uploaded for.", ""]
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1])
