// Shared scaffold for the JSON-API portals (generated by scratchpad/gen_portals.py — edit the
// generator, not this file). Zero runtime dependencies: Bun's fetch + JSON.

export interface SearchOpts {
  query?: string
  location?: string
  country?: string   // ISO-3166 alpha-2, upper-case (worldwide boards only)
  jobage?: number    // 1 | 7 | 14 | 30
  page: number       // 1-indexed
  limit: number
  extra: Record<string, string>
}

/** The portal contract row. Extra fields are a permitted superset; missing values are null. */
export interface Row {
  id: string
  title: string
  company: string | null
  location: string | null
  date: string | null   // YYYY-MM-DD
  url: string
  [k: string]: unknown
}

export interface SearchResult {
  meta: { page: number; limit: number; total?: number | null; [k: string]: unknown }
  results: Row[]
}

export class CliError extends Error {
  constructor(message: string, public code: string) {
    super(message)
  }
}

export function writeError(error: string, code: string): void {
  process.stderr.write(JSON.stringify({ error, code }) + "\n")
}

export const UA = "job-search-engine/1.0 (+https://github.com/DevAdamExp/job-search-engine)"

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}

/**
 * Fetch JSON with a 20 s timeout. 429 / 5xx retry with backoff (max 4 tries); 404 → null;
 * other 4xx throw with the body's message. Connection failures fail fast (graceful degradation:
 * one dead board must not hang the multi-board search).
 */
export async function fetchJson<T = unknown>(url: string, init: RequestInit = {}, opts: { retries?: number; minDelay?: number } = {}): Promise<{ body: T | null; headers: Headers; status: number }> {
  const retries = opts.retries ?? 3
  let delay = opts.minDelay ?? 600
  for (let attempt = 0; ; attempt++) {
    let res: Response
    try {
      res = await fetch(url, {
        ...init,
        headers: { "User-Agent": UA, Accept: "application/json", ...(init.headers as Record<string, string> | undefined) },
        redirect: "follow",
        signal: AbortSignal.timeout(20000),
      })
    } catch (e) {
      throw new CliError(`could not reach ${new URL(url).host}: ${e instanceof Error ? e.message : String(e)}`, "UNREACHABLE")
    }
    if ((res.status === 429 || res.status >= 500) && attempt < retries) {
      await sleep(delay + Math.floor(Math.random() * 300))
      delay = Math.min(delay * 2, 8000)
      continue
    }
    if (res.status === 404) return { body: null, headers: res.headers, status: 404 }
    const text = await res.text()
    let body: unknown = null
    try { body = text ? JSON.parse(text) : null } catch { body = null }
    if (!res.ok) {
      const msg = (body && typeof body === "object" && ("message" in body || "error" in body))
        ? String((body as Record<string, unknown>).message ?? (body as Record<string, unknown>).error) : text.slice(0, 200)
      throw new CliError(`${new URL(url).host} answered ${res.status}: ${msg || res.statusText}`, res.status === 401 || res.status === 403 ? "AUTH" : "HTTP_" + res.status)
    }
    if (body === null && text.trim()) throw new CliError(`${new URL(url).host} returned non-JSON output`, "BAD_OUTPUT")
    return { body: body as T, headers: res.headers, status: res.status }
  }
}

/** YYYY-MM-DD from an ISO string, a unix timestamp (s or ms) or a dd/mm/yyyy string; null when unparseable. */
export function isoDate(v: unknown): string | null {
  if (v == null || v === "") return null
  if (typeof v === "number") {
    const ms = v > 1e12 ? v : v * 1000
    const d = new Date(ms)
    return isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10)
  }
  const s = String(v).trim()
  let m = s.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (m) return `${m[1]}-${m[2]}-${m[3]}`
  m = s.match(/^(\d{2})\/(\d{2})\/(\d{4})/)
  if (m) return `${m[3]}-${m[2]}-${m[1]}`
  const d = new Date(s)
  return isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10)
}

/** True when `date` (YYYY-MM-DD) is within the last `days` days (inclusive); undated rows fail. */
export function withinDays(date: string | null, days: number | undefined, today = new Date()): boolean {
  if (!days) return true
  if (!date) return false
  const t = Date.parse(date + "T00:00:00Z")
  if (isNaN(t)) return false
  // whole calendar days (UTC): a posting dated yesterday is "within 1 day" all of today
  const todayMidnight = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate())
  return Math.round((todayMidnight - t) / 86400000) <= days
}

/** Strip HTML to readable text (block tags → newlines, entities decoded). Null for empty input. */
export function cleanHtml(html: string | null | undefined): string | null {
  if (!html) return null
  const text = html
    .replace(/<\s*br\s*\/?>/gi, "\n")
    .replace(/<\/(p|li|ul|ol|div|h\d|tr)>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, " ")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/[ \t]+/g, " ").replace(/ *\n */g, "\n").replace(/\n{3,}/g, "\n\n").trim()
  return text || null
}

export function money(min: unknown, max: unknown, currency?: string | null, period?: string | null): string | null {
  let a = typeof min === "number" ? min : null
  let b = typeof max === "number" ? max : null
  if (a == null && b == null) return null
  if (a != null && b != null && a > b) [a, b] = [b, a]
  const cur = currency ? `${currency} ` : ""
  const range = a != null && b != null && a !== b ? `${a.toLocaleString("en")}–${b.toLocaleString("en")}` : (a ?? b)!.toLocaleString("en")
  return `${cur}${range}${period ? ` ${period}` : ""}`
}

/** Require an env var (API key); a missing one is a clear CONFIG error, never a silent empty result. */
export function requireEnv(name: string): string {
  const v = (process.env[name] ?? "").trim()
  if (!v) throw new CliError(`${name} is not set (this board needs an API key; see SKILL.md)`, "CONFIG")
  return v
}

/** Case-insensitive "every query word appears in the haystack" — for boards without a keyword parameter. */
export function matchesQuery(query: string | undefined, ...fields: (string | null | undefined)[]): boolean {
  if (!query) return true
  const hay = fields.filter(Boolean).join(" ").toLowerCase()
  return query.toLowerCase().split(/\s+/).filter(Boolean).every((w) => hay.includes(w))
}

/** Country names for boards that only take free-text locations. */
export const COUNTRY_NAMES: Record<string, string> = {
  AE: "United Arab Emirates", AT: "Austria", AU: "Australia", BD: "Bangladesh", BE: "Belgium", BR: "Brazil", CA: "Canada",
  CH: "Switzerland", CN: "China", CZ: "Czechia", DE: "Germany", DK: "Denmark", ES: "Spain", FI: "Finland", FR: "France",
  GB: "United Kingdom", HK: "Hong Kong", IE: "Ireland", IN: "India", IT: "Italy", JP: "Japan", KR: "South Korea",
  KW: "Kuwait", LU: "Luxembourg", MX: "Mexico", MY: "Malaysia", NL: "Netherlands", NO: "Norway", NZ: "New Zealand",
  OM: "Oman", PH: "Philippines", PK: "Pakistan", PL: "Poland", PT: "Portugal", QA: "Qatar", SA: "Saudi Arabia",
  SE: "Sweden", SG: "Singapore", TR: "Türkiye", US: "United States", ZA: "South Africa",
}

export function renderTable(rows: Row[]): string {
  const cut = (s: unknown, n: number) => { const t = s == null ? "" : String(s); return t.length > n ? t.slice(0, n - 1) + "…" : t }
  const lines = [`${"date".padEnd(10)}  ${"title".padEnd(48)}  ${"company".padEnd(28)}  location`]
  for (const r of rows) lines.push(`${cut(r.date, 10).padEnd(10)}  ${cut(r.title, 48).padEnd(48)}  ${cut(r.company, 28).padEnd(28)}  ${cut(r.location, 30)}`)
  return lines.join("\n")
}

export function renderPlain(rows: Row[]): string {
  return rows.map((r) => [r.title, `${r.company ?? "—"} · ${r.location ?? "—"}${r.date ? ` · ${r.date}` : ""}`, r.url].join("\n")).join("\n\n")
}
